PROGRAM RUNGEKUTTA
  IMPLICIT NONE
  REAL :: X,Y,XP,H,K1,K2,K3,K4,F
  INTEGER :: N, INT, I
  WRITE(*,*) "INPUT VALUES OF X AND Y"
  READ(*,*) X,Y
  WRITE(*,*) "INPUT VALUES OF X AT WHICH Y IS REQUIRED"
  READ(*,*) XP
  WRITE(*,*) "INPUT SIZE H"
  READ(*,*) H

  N = INT((XP-X)/H)
  WRITE(*,*) N

  DO I=1,N
  K1 = H*F(X,Y)
  K2 = H*F(X+0.5*H,Y+0.5*K1)
  K3 = H*F(X+0.5*H,Y+0.5*K2)
  K4 = H*F(X+H,Y+K3)
  X=X+H
  Y=Y+(K1+2.0*K2+2*K3+K4)*(1/6.0)
  WRITE(*,*) I,X,Y
  END DO

  WRITE(*,*) "VALUE OF Y AT X=",X,"IS",Y
END PROGRAM RUNGEKUTTA

REAL FUNCTION F(X,Y)
  REAL :: X,Y
  F=2*X
END FUNCTION
